service: prometheus

env: flex
runtime: go1.10

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Must use an unprotected URL for liveness and readiness checks

liveness_check:
  path: "/graph"
  check_interval_sec: 300
  timeout_sec: 10
  failure_threshold: 10
  success_threshold: 2
  initial_delay_sec: 300

readiness_check:
  path: "/graph"
  check_interval_sec: 300
  timeout_sec: 300
  failure_threshold: 10
  success_threshold: 2
  app_start_timeout_sec: 3600

# Define credentials as environment variables
#includes:
#- env.yaml

#skip_files:
#- ^vendor/.*$
#- ^vendor.zip$
